version: '3.8'

services:
  ms-api-gateway-test:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=test
      - JWT_SECRET=123456
      - PORT=4000
    networks:
      - ms-network
    command: npm test
    depends_on:
      - ms-auth-mock
      - ms-book-mock
      - ms-notification-mock

  ms-auth-mock:
    image: mockoon/cli:latest
    command: -d /data/auth-mock.json -p 3000
    volumes:
      - ./mocks:/data
    networks:
      - ms-network

  ms-book-mock:
    image: mockoon/cli:latest
    command: -d /data/book-mock.json -p 3001
    volumes:
      - ./mocks:/data
    networks:
      - ms-network

  ms-notification-mock:
    image: mockoon/cli:latest
    command: -d /data/notification-mock.json -p 3002
    volumes:
      - ./mocks:/data
    networks:
      - ms-network

networks:
  ms-network:
    driver: bridge